### ISSUE TITLE
LEX0001: I DON'T LIKE TULIPS

### ISSUE THREAD

**Issue by edilsalvador** [lecsical/sample#4]
Can you please delete the tulips, I want roses. Upload some roses :rose: :rose: :rose:

**Comment by clinomania** [comment]
May roses na po xD

**Comment by edilsalvador** [comment]
Thank you, kaso andun pa din yung Tulips...

**Comment by clinomania** [comment]
Sorry! Di marunong magbasa xD

**Comment by clinomania** [comment]
Nadelete na po

**Comment by clinomania** [comment]
Ay di pa pala totally nadedelete. May delete request akong ginawa :D

**Comment by edilsalvador** [comment]
Pak! Ganern lang! HAHAHA. Close ko na to xD
