### ISSUE TITLE
Nakakabother yung picture na maganda daw siya xD

### ISSUE THREAD

**Issue by clinomania** [lecsical/sample#7]
Paalis nung pic, pabago. Pagawang picture ko tapos same caption HAHAHHAHAHAHAAHA

**Comment by edilsalvador** [comment]
Imposible yung pangalawang statement. Sorry. HAHAHA. Pero aalisin ko na yung picture ko. Hindi naman kabog tong repository na to e, kaya hindi bagay yun :D

**Comment by edilsalvador** [comment]
Naalis ko na yung picture na maganda ako, hindi ko talaga ma-upload picture mo na may same caption e xD Sorry talaga. HAHAHAHA

**Comment by clinomania** [comment]
AHAHHAHAHAHA Hindi ko to iko-close hanggat hindi na-a-up yung picture ko HAHAHAH. Joke. xD Close ko na nga tong kalokohan na to. Thank you!
